import * as fs from "node:fs";
import * as path from "node:path";

/*
 * CLAUDE.md merge state machine:
 *
 *  ┌───────────────────────────────────────────────────────────┐
 *  │                  CLAUDE.md merge states                    │
 *  ├──────────────────────────┬───────────────────────────────┤
 *  │ Input state              │ Action                         │
 *  ├──────────────────────────┼───────────────────────────────┤
 *  │ No file                  │ Write fresh file               │
 *  │ Has decidex markers      │ Replace between markers only   │
 *  │ Exists, no markers       │ Prepend decidex section,       │
 *  │                          │ preserve all existing content  │
 *  └──────────────────────────┴───────────────────────────────┘
 *
 * Markers (public API — do NOT change without a migration):
 *   <!-- decidex:start -->
 *   <!-- decidex:end -->
 */

const MARKER_START = "<!-- decidex:start -->";
const MARKER_END = "<!-- decidex:end -->";

/** Build the decidex section content to inject. */
function buildDecidexSection(decisions: string[]): string {
  if (decisions.length === 0) {
    return [
      MARKER_START,
      "",
      "## Engineering Decisions (managed by decidex)",
      "",
      "_No decisions captured yet. Run `decidex generate` to extract decisions from git history._",
      "",
      MARKER_END,
    ].join("\n");
  }

  const items = decisions.map((d) => `- ${d}`).join("\n");
  return [
    MARKER_START,
    "",
    "## Engineering Decisions (managed by decidex)",
    "",
    "_Auto-generated by [decidex](https://github.com/decidex/decidex). Edit with `decidex generate`._",
    "",
    items,
    "",
    MARKER_END,
  ].join("\n");
}

/**
 * Merge decidex content into CLAUDE.md atomically.
 * Preserves all user-written content outside the decidex markers.
 */
export function mergeCLAUDEMD(filePath: string, decisions: string[]): MergeResult {
  const section = buildDecidexSection(decisions);

  if (!fs.existsSync(filePath)) {
    // State: no file → write fresh
    atomicWrite(filePath, section + "\n");
    return { state: "created", preserved: 0 };
  }

  const existing = fs.readFileSync(filePath, "utf8");
  const startIdx = existing.indexOf(MARKER_START);
  const endIdx = existing.indexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
    // State: has markers → replace only the decidex section
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + MARKER_END.length);
    const merged = before + section + after;
    atomicWrite(filePath, merged);
    return {
      state: "updated",
      preserved: before.trim().length + after.trim().length,
    };
  }

  // State: file exists, no markers → prepend decidex section
  const merged = section + "\n\n" + existing;
  atomicWrite(filePath, merged);
  return { state: "prepended", preserved: existing.trim().length };
}

/** Write content to a file atomically via temp-file + rename. */
function atomicWrite(filePath: string, content: string): void {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  // Write temp file in the same directory as target to guarantee same-filesystem rename
  const tmp = path.join(dir, `.decidex-${Date.now()}.tmp`);
  fs.writeFileSync(tmp, content, "utf8");
  fs.renameSync(tmp, filePath);
}

export interface MergeResult {
  /** What action was taken */
  state: "created" | "updated" | "prepended";
  /** Byte length of preserved user content (0 for new files) */
  preserved: number;
}
