import * as fs from "node:fs";
import * as path from "node:path";

/*
 * Tool injector — writes engineering decisions to AI tool context files.
 *
 * Supported targets:
 *   cursor   → .cursor/rules/decidex.mdc
 *   copilot  → .github/copilot-instructions.md
 *   windsurf → .windsurfrules
 *
 * Each target writes ONLY the decidex section, bounded by markers so it can
 * be re-injected without clobbering user content in the same file.
 *
 * Markers (public API — do NOT change without a migration):
 *   <!-- decidex:start -->
 *   <!-- decidex:end -->
 */

const MARKER_START = "<!-- decidex:start -->";
const MARKER_END = "<!-- decidex:end -->";

export type InjectionTarget = "cursor" | "copilot" | "windsurf";

export interface InjectionResult {
  target: InjectionTarget;
  filePath: string;
  state: "created" | "updated" | "prepended";
}

/** Build the decidex section body (without markers). */
function buildSection(decisions: string[]): string {
  if (decisions.length === 0) {
    return "## Engineering Decisions (managed by decidex)\n\n_No decisions captured yet. Run `decidex generate`._\n";
  }
  const items = decisions.map((d) => `- ${d}`).join("\n");
  return (
    "## Engineering Decisions (managed by decidex)\n\n" +
    "_Auto-generated by [decidex](https://github.com/decidex/decidex). Edit with `decidex generate`._\n\n" +
    items +
    "\n"
  );
}

/** Inject (or update) the decidex block in a file, preserving surrounding content. */
function injectIntoFile(filePath: string, decisions: string[]): "created" | "updated" | "prepended" {
  const section = `${MARKER_START}\n${buildSection(decisions)}${MARKER_END}`;
  const dir = path.dirname(filePath);

  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(dir, { recursive: true });
    atomicWrite(filePath, section + "\n");
    return "created";
  }

  const existing = fs.readFileSync(filePath, "utf8");
  const startIdx = existing.indexOf(MARKER_START);
  const endIdx = existing.indexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + MARKER_END.length);
    atomicWrite(filePath, before + section + after);
    return "updated";
  }

  // Prepend to preserve existing user content
  atomicWrite(filePath, section + "\n\n" + existing);
  return "prepended";
}

/** Write file atomically (same-directory temp file → rename). */
function atomicWrite(filePath: string, content: string): void {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  const tmp = path.join(dir, `.decidex-${Date.now()}.tmp`);
  fs.writeFileSync(tmp, content, "utf8");
  fs.renameSync(tmp, filePath);
}

/** Inject decisions into a Cursor rules file (.cursor/rules/decidex.mdc). */
function injectCursor(repoRoot: string, decisions: string[]): InjectionResult {
  const filePath = path.join(repoRoot, ".cursor", "rules", "decidex.mdc");
  const dir = path.dirname(filePath);

  // Cursor .mdc format requires frontmatter
  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(dir, { recursive: true });
    const section = `${MARKER_START}\n${buildSection(decisions)}${MARKER_END}`;
    const content = [
      "---",
      "description: Engineering decisions for this project (managed by decidex)",
      "globs:",
      "  - '**/*'",
      "alwaysApply: true",
      "---",
      "",
      section,
      "",
    ].join("\n");
    atomicWrite(filePath, content);
    return { target: "cursor", filePath, state: "created" };
  }

  const state = injectIntoFile(filePath, decisions);
  return { target: "cursor", filePath, state };
}

/** Inject decisions into GitHub Copilot instructions (.github/copilot-instructions.md). */
function injectCopilot(repoRoot: string, decisions: string[]): InjectionResult {
  const filePath = path.join(repoRoot, ".github", "copilot-instructions.md");
  const state = injectIntoFile(filePath, decisions);
  return { target: "copilot", filePath, state };
}

/** Inject decisions into Windsurf rules (.windsurfrules). */
function injectWindsurf(repoRoot: string, decisions: string[]): InjectionResult {
  const filePath = path.join(repoRoot, ".windsurfrules");
  const state = injectIntoFile(filePath, decisions);
  return { target: "windsurf", filePath, state };
}

const INJECTORS: Record<InjectionTarget, (repoRoot: string, decisions: string[]) => InjectionResult> = {
  cursor: injectCursor,
  copilot: injectCopilot,
  windsurf: injectWindsurf,
};

/**
 * Inject decisions into one or more AI tool context files.
 * @param repoRoot  Absolute path to the repo root
 * @param decisions List of decision text strings to inject
 * @param targets   Which tools to inject into (default: all three)
 */
export function injectDecisions(
  repoRoot: string,
  decisions: string[],
  targets: InjectionTarget[] = ["cursor", "copilot", "windsurf"]
): InjectionResult[] {
  return targets.map((t) => INJECTORS[t](repoRoot, decisions));
}
